[project]
name = "03-1-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm[proxy]>=1.85.1",
    "openai-agents[litellm]>=0.0.19",
    "python-dotenv",
    "streamlit",
    "fastmcp",
    "temporalio",
]
